___

<a href='http://www.pieriandata.com'> <img src='https://www.python.org/static/community_logos/python-logo-master-v3-TM.png' /></a>
___

## NumPy Arrays

Often comes as vectors as 1D (1 blacket) and matrics as 2D (2 blackets)

* Array
    * Array 1D and 2D (matrix)
    * Range array (arange)
    * Zero array 1D and 2D (np.zeros)
    * All one array 1D and 2D (np.ones)
    * Array with evenly space (np.linspace)
    * One diagonal Identity matrix (np.eyes)
* Random Array
    * Random array 1D and 2D (np.random.rand)
    * Normal Distribution 1D and 2D (np.random.randn)
    * Pick 1 random number from array (np.random.randint)
* Reshape
    * Reshape matrix (x.reshape)
* Find Max and Min
    * Max value in array (x.max)
    * Min value in array (x.min)
    * Location of max value in array (x.argmax)
    * Location of min value in array (x.argmin)
* Find shape of array
    * Find shape (x.shape)
    * Find data type (x.dtype)

In [1]:
my_list = [1,2,3]

In [2]:
my_list # return as list

[1, 2, 3]

In [3]:
import numpy as np # import numpy package library

In [4]:
np.array(my_list) # return as array (1D)

array([1, 2, 3])

In [5]:
arr = np.array(my_list) # cast to variable (1D array)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]] # create list of lists

In [8]:
np.array(my_mat) # ruturn as array (2D you will see 2 blankets) 3 rows 3 columns

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
np.arange(10) # get array of range same as range function start 0 end 9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
# similar to range function
list(range(2,10)) # convert range to list but not in array

[2, 3, 4, 5, 6, 7, 8, 9]

In [62]:
np.arange(2,10) # get array of range same as range function start 2 end 9

array([2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,10,2) # get only even (step increment of 2)

array([0, 2, 4, 6, 8])

In [11]:
np.zeros(3) # return zero array (1D)

array([0., 0., 0.])

In [12]:
np.zeros((5,6)) # input tuple return 5 rows and 6 column
# tuple input

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [13]:
np.ones(2) # return one array (1D)

array([1., 1.])

In [14]:
np.ones((3,2)) # input tuple return 3 rows and 2 column
# tuple input

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [15]:
np.linspace(0,5,10) # return 1D vector 10 evenly spaces from 0-5

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [16]:
np.linspace(0,5,20) # return 1D vector 20 evenly spaces from 0-5

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [17]:
np.eye(4) # return square (4x4) Identity metrix (1 diagonal) 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Random array

In [18]:
np.random.rand(5) # return 1D random number array from 0-1 (decimal)

array([0.82356711, 0.35430852, 0.11472777, 0.36474954, 0.97691126])

In [19]:
np.random.rand(5,3) # return 2D random number 5 rows 3 columns array from 0-1 

array([[0.83281507, 0.14333104, 0.78377869],
       [0.82627893, 0.86583279, 0.76067259],
       [0.59579123, 0.83452494, 0.1515115 ],
       [0.65103336, 0.91627448, 0.19792365],
       [0.21827909, 0.15600293, 0.47714719]])

In [43]:
np.random.randn(2) # return 1D random number from std. normal distribution (Gaussian)

array([-0.67149897,  0.82516002])

In [21]:
np.random.randn(2,2) # return 2D random number from std. normal distribution (Gaussian)

array([[0.87973938, 2.77075933],
       [0.2134485 , 0.34827734]])

In [22]:
np.random.randint(1,400) # return 1 random integer between 1 to 399
# exclusive for high end

90

In [51]:
np.random.randint(1,400,10) # return 10 random integers (in array) between 1 to 399
#inclusive for low end, exclusive for high end

array([245, 173,  23, 228, 287,  93, 287,  70, 133, 149])

### Reshape

In [24]:
arr1 = np.arange(25)

In [25]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [55]:
arr2 = np.random.randint(0,50,10)

In [56]:
arr2

array([30, 44, 32, 22, 19,  2, 37, 35, 27,  0])

In [49]:
arr1.reshape(5,5) # reshape that array to be 5x5 (the number of value from original array should match)

# from arr1 = 25 so should be (5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### Find Max and Min

In [29]:
arr2

array([ 6,  7, 30, 21, 41,  4, 45, 13, 37, 18])

In [30]:
arr2.max() # find the max value of array

45

In [31]:
arr2.min() # find the min value of array

4

In [32]:
arr2.argmax() # find the position of max value (48) in that array 

6

In [33]:
arr2.argmin() # find the position of min value (4) in that array

5

### Find shape of array

In [34]:
arr1.shape # return a shape of the array (still 1D for arr1)

(25,)

In [35]:
arr1 = arr1.reshape(5,5)

In [36]:
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
arr1.shape #now it's 2D

(5, 5)

In [38]:
arr.dtype # return type of an array

dtype('int64')