___

<a href='http://www.pieriandata.com'> <img src='https://www.python.org/static/community_logos/python-logo-master-v3-TM.png' /></a>
___

# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

* Bracket Indexing and Selection
    * Get a value at an index
* Broadcasting
    * Broadcast array
    * Slicing
    * Copy methiod (x.copy)
* Indexing a 2D array (matrics)
    * Index row 
    * Index value
    * Array slicing
* Fancy indexing
* Selection

In [2]:
import numpy as np

In [21]:
#Creating sample array
arr = np.arange(0,11)

In [22]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:
* This one return as a list in the from of array so it differ

In [49]:
#Get a value at an index
arr[8]

8

In [50]:
#Get values in a range this one from 2 to 4 (exclusive at high end)
arr[2:5]

array([100, 100, 100])

In [51]:
#Get values in a range this one from 0 to 4 (exclusive at high end)
arr[:5]

array([100, 100, 100, 100, 100])

In [52]:
#Get values in a range this one from 5 and beyond
arr[5:]

array([99,  6,  7,  8,  9, 10])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [53]:
arr # from np.arange

array([100, 100, 100, 100, 100,  99,   6,   7,   8,   9,  10])

In [54]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show -> replace first 5 value to be 100 
arr

array([100, 100, 100, 100, 100,  99,   6,   7,   8,   9,  10])

In [55]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

In [56]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show cut down version the value except the first six
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [58]:
arr 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Now note the changes also occur in our original array!

In [60]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [61]:
#To get a copy, need to be explicit (copy method)
arr_copy = arr.copy()

arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [62]:
arr_copy # same as arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [63]:
arr_copy[:] = 100 # if we try broadcast the copied
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [64]:
arr # original array still uneffected


array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [65]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [66]:
#Indexing row
arr_2d[1]


array([20, 25, 30])

In [67]:
# Index value
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [68]:
# Getting individual element value (the result is the same)
arr_2d[1,0]

20

In [78]:
# 2D array slicing
"""      0    1   2
    0   [5,  10, 15] 
    1   [20, 25, 30]
    2   [35, 40, 45]
"""
#Shape (2,2) from top right corner
# return row 0 and 1 (up to 2)
# return from column 1 onwards

arr_2d[:2,1:]  

array([[10, 15],
       [25, 30]])

In [77]:
#Shape (2,2) from low left corner
"""      0    1   2
    0   [5,  10, 15] 
    1   [20, 25, 30]
    2   [35, 40, 45]
"""
# return row 1 onwards
# return column 0 and 1 (up to 2)
    

arr_2d[1:,:2]  

array([[20, 25],
       [35, 40]])

In [19]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [20]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

In [95]:
e = np.arange(50).reshape(5,10)
e

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [96]:
e[1:3,3:5]

array([[13, 14],
       [23, 24]])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [99]:
#Set up matrix
arr2d = np.zeros((10,10))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [100]:
#Length of array
arr_length = arr2d.shape[1]

In [101]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

Fancy indexing allows the following

In [24]:
arr2d[[2,4,6,8]]

array([[ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.]])

In [25]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.]])

## More Indexing Help
Indexing a 2d matrix can be a bit confusing at first, especially when you start to add in step size. Try google image searching NumPy indexing to fins useful images, like this one:

<img src= 'http://memory.osu.edu/classes/python/_images/numpy_indexing.png' width=500/>

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [80]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [81]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [88]:
bool_arr = arr>4

In [89]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [90]:
arr[bool_arr] # return only TRUE

array([ 5,  6,  7,  8,  9, 10])

In [91]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [92]:
arr[arr<3]

array([1, 2])

In [93]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# Great Job!
